title: Adair County Humane Society
description: "Adair County Humane Society"
baseurl: "/"
url: "http://adaircountyhumanesociety.github.io"

markdown: kramdown

plugins:
    - jekyll-bootstrap-sass

sass:
    style: compressed